### PR TITLE
MNT: Re-rendered with conda-smithy 2.3.3

### PR DESCRIPTION
**Pull request by pmlandwehr**

### CODE REVIEW

**Comment by pmlandwehr** [comment]
ping @conda-forge/funcsigs

**Comment by pmlandwehr** [comment]
Another ping to @conda-forge/funcsigs - can we get this regeneration merged if you have a second?

**Comment by jakirkham** [comment]
Yep, sorry, must have missed this on the first ping.

**Comment by jakirkham** [comment]
Thanks @pmlandwehr.

As a side note, we are on `conda-smithy` 2.4.0 now. Though I don't expect any substantial changes between what you have already PR'd.

**Pull request merged**
